name: Build App

on:
  push:
    branches:
      - main   # Lance le workflow à chaque push sur main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer ton code
      - uses: actions/checkout@v2

      # Étape 2 : Construire et pousser ton image Docker
      - name: Build and Push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          repository: mrcoco28/cd   # <-- mets ton pseudo DockerHub ici
          tag_with_sha: true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - uses: 3r1co/dependency-check-action@master
        name: OWASP Dependency Check
        with:
          Project-Name: TestApp

      - name: Archive dependency check reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
