name: Build App

on:
  push:
    branches:
      - main   # Lance le workflow à chaque push sur main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer ton code
      - uses: actions/checkout@v2

      # Étape 2 : Construire et pousser ton image Docker
      - name: Build and Push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          repository: mrcoco28/cd   # ton DockerHub repo
          tag_with_sha: true

      # Étape 3 : Analyse avec SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=mrcoco28_cd   # ton Project Key SonarCloud
            -Dsonar.organization=mrcoco28    # ton organisation SonarCloud
            -Dsonar.host.url=https://sonarcloud.io
